### ISSUE TITLE
Not handled response Bad Request from spoke site.

### ISSUE THREAD

**Issue by grogou** [10up/distributor#488] opened 2019-11-19 15:03 UTC
**Is your enhancement related to a problem? Please describe.**
When I'm distributing post to a website, which actually is down, I still get a "post successfully distributed" message.

**Describe the solution you'd like**
Currently, we are handling only the case, when response  `status code` is `400`, `Bad request`, In other cases, for example, 403, 504, etc we will show "post successfully distributed", I suggest to handle them as an error like `Bad request and show error message, this will also allow retrying distribution later.

**Designs**
n/a

**Describe alternatives you've considered**
I think it's even better to use post_id, to identify if the post was successfully distributed or not, so, if we have received post_id on target, we can say distribution was successful, otherwise, show error message.

**Additional context**
Tested for external connections only.

**Comment by jeffpaul** [comment] 2019-11-20 20:35
@eriktad welcome to Distributor and thanks for the feedback!  I don't know that we can rely on post_id matching on the destination site(s), but otherwise would be open to a PR on this in a future release if you're able to craft a solution for this?

**Comment by grogou** [comment] 2019-11-22 07:54
@jeffpaul Thank you too!
@tlovett1 
In the case, where the response body is not empty and I have only  
```
["data"]=>
  {
    ["status"] => 400
  }
```
this is a case if the received response is `Bad request`, This try/catch is not working if PHP notice and warnings switched off.

https://github.com/10up/distributor/blob/025cc7ea5e8e693ad35f676809cd95e2e093cb78/includes/classes/ExternalConnections/WordPressExternalConnection.php#L650-L654

 PHP works without an undefined index notice, and we don't receive an exception, we receive `remote_id = NULL`.

**Comment by dinhtungdu** [comment] 2020-02-02 08:45
@eriktad Can you add instruction to reproduce this issue. I tried to distribute post to a down site but I couldn't reach the try-catch block at line 650, the `push` function got returned at line 537.

**Comment by jeffpaul** [comment] 2020-03-26 13:57
@eriktad can you confirm your steps to reproduce this issue as we've been unable to reproduce it?  I'm moving this to `Future Release` until we're able to reproduce the issue and if so then determine a resolution.  I agree that if we are able to reproduce this that its something we should address, its just not something we've been able to reproduce as of yet.

**Comment by arsendovlatyan** [comment] 2020-03-30 09:41
@dinhtungdu you are right, taking entire site down, won't bring up this issue, however, here is how I have reproduced it just now.
- I went to destination website and changed "distributor" user (which I'm using for external connection) permission to "subscriber", so, it won't be able to create posts
- opened the source website and pushed a post, it shows "success"message 
- but in fact, post was not created in destination
- i have this in connection map, as you can see, remote post ID is 0
```a:2:{s:8:"external";a:1:{i:122202;a:2:{s:7:"post_id";i:0;s:4:"time";i:1585560777;}}s:8:"internal";a:0:{}}```

This because we use `try` to check if ` $body_array['id'] ` exists, instead of `isset` or `empty` functions.

**Comment by dinhtungdu** [comment] 2020-03-31 00:33
@arsendovlatyan Thanks so much for the instruction, I can confirm the issue now.

**Closed as completed** 2020-04-10 16:06 UTC
Labels: type:enhancement, needs:feedback
