### ISSUE TITLE
webp images dont pull for woocommerce

### ISSUE THREAD

**Issue by ScrewlooseA** [10up/distributor#1144] opened 2023-10-11 11:04 UTC
### Describe the bug

Alot of the products have come in without any feature image when distributed. I have narrowed it down to all those that have a webp image format on the master website

example:
https://telechoice.com.au/shop/accessories/phone-cases-accessories/defense-dash-ip-x-xs-black-leather/ - has images (all webp format)
https://shop.screwlooseit.com.au/index.php/product/defense-dash-ip-x-xs-black-leather/ - has no image

### Steps to Reproduce

place a webp image on a product in master site
push the product to another site

no image pushes.

try pull instead - same issue

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by willemb2** [comment] 2024-08-22 17:06
This is a duplicate of #810 but I like the label 'bug' it gets here.

**Comment by jeffpaul** [comment] 2024-08-27 14:28
Closing in favor of #810 that I just pulled into our near term roadmap to work on

**Closed as not planned by jeffpaul** 2024-08-27 14:28 UTC
Labels: type:bug
