### ISSUE TITLE
Unpublish ditributed post

### ISSUE THREAD

**Issue by isuke01** [10up/distributor#1138] opened 2023-09-19 09:20 UTC
### Describe the bug

In relation to #990
Now when the original post is unpublished the distributed posts will stay in old status.
This is kind of problematic.
If that is an expected behaviour, maybe we could just have option for this?

From client's perspective all distributed posts should follow the original one, so if the original has hanged status -> **unpublished**, **private**, **pass protected** etc, all should follow. But as it is now they don't. It is counterintuitive.

Additionally when Original post is in draft status when updated and still save to draft the distributed post will get this update.

### Steps to Reproduce

1. Create post and distribute.
2. Unpublish original post. 
3. Distributed one are still published.
4. Apply any changes to original post while draft in draft and save as draft.
5. Go to distributed post - it will received the update while still in publish status.

### Environment information

- **PHP** ~8.2
- **WP**: 6.1.3
- **Distributor**: 2.0.1
- Chrome, mac OS.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jeffpaul** [comment] 2023-09-19 19:40
@isuke01 Distributor currently does not distribute post status changes, by design, though you can follow #112 to see as we work on potentially supporting that behavior.  As such, I'm closing this issue as a duplicate of 112.

**Closed as not planned by jeffpaul** 2023-09-19 19:40 UTC
Labels: type:bug
