### ISSUE TITLE
WPML

### ISSUE THREAD

**Issue by ligne13** [10up/distributor#887] opened 2022-06-02 15:50 UTC
### Is your enhancement related to a problem? Please describe.

Hi,

I have read https://github.com/10up/distributor/issues/382, and made some tests in my network with Distributor and WPML. Currently it does not work. The translations of pages are not distributed with the source page.
Do you plan on update the plugin in order to handle WPML properly ?

Thanks.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jeffpaul** [comment] 2022-06-03 02:39
@ligne13 we are not immediately planning to work on a specific WPML integration, no.  As noted briefly in https://github.com/10up/distributor/issues/382#issuecomment-498734622, have you tried distributing the translated posts to see if Distributor keeps those in sync along with the origin WPML post?  Either way, if this is of particularly urgent or important functionality for you then please reach out (jeff.paul@10up.com) and we can discuss options to customize Distributor for you.  In either case, I'm closing this as a duplicate of #382.

**Closed as completed by jeffpaul** 2022-06-03 02:39 UTC
Labels: type:question
