### ISSUE TITLE
Could not pull content from connection due to error. API endpoint error.

### ISSUE THREAD

**Issue by IonTulbure** [10up/distributor#1232] opened 2024-06-17 13:17 UTC
### Describe the bug

Distributor stable Version 2.0.4. 

I can establish connection from site X to site Y on a Shared Hosting (Hostinger)

![image](https://github.com/10up/distributor/assets/42011629/82a4d447-a6b4-4361-adac-54e91f7c4a07)

![image](https://github.com/10up/distributor/assets/42011629/b9edce54-0c05-4d12-8a73-5b27421f5721)

However at Pull Content screen i get this error: 

```Could not pull content from connection due to error. API endpoint error.```

![image](https://github.com/10up/distributor/assets/42011629/f05ed19a-35b4-43bb-b335-b8d529173c09)

---

On both of these 2 websites i get the following error (Query Monitor)

```
Post: https://site.xyz/wp-json/wp/v2/distributor/list-pull-content  (confidential)
500 Internal Server Error
Caller: 
Distributor\ExternalConnections\WordPressExternalConnection->remote_post()
wp-content/plugins/distributor-stable/includes/classes/ExternalConnections/WordPressExternalConnection.php:243
Distributor\ExternalConnections\WordPressExternalConnection->remote_get()
wp-content/plugins/distributor-stable/includes/classes/ExternalConnections/WordPressExternalConnection.php:176
Distributor\PullListTable->prepare_items()
wp-content/plugins/distributor-stable/includes/classes/PullListTable.php:530
Distributor\PullUI\dashboard()
wp-content/plugins/distributor-stable/includes/pull-ui.php:529
do_action('distributor_page_pull')
wp-includes/plugin.php:517 
Component: Plugin: distributor-stable
```

Besides Distributor everything works fine and fast. Hosting has enough resources.
I tried to deactivate other plugins and change theme but it gave no result. 
Also i switched between various PHP versions (7.4 -> 8.1) and also no luck. 

On both sites Rest Api is available : 
![image](https://github.com/10up/distributor/assets/42011629/e3daa32c-b80a-43aa-b8f8-90360328e016)

### Steps to Reproduce

1. Establish connection between sites
2. Go to Pull Content screen
3. Use Query Monitor to catch errors 
![image](https://github.com/10up/distributor/assets/42011629/f05ed19a-35b4-43bb-b335-b8d529173c09)

### Screenshots, screen recording, code snippet

_See Description_

### Environment information

Env info: 
```
Wordpress: 6.5.4
SSl: yes
Web Server: LiteSpeed
PHP: 8.1.27 (Supports 64bit values)
PHP memory: 	2048M
PHP max input variables	5000
PHP time limit	360
Max input time	360
cURL version	7.87.0 OpenSSL/1.1.1w
Extension	mysqli
Server version	10.11.7-MariaDB-cll-lve
```

### WordPress information

```

Version	6.5.4
Site Language	en_US
User Language	en_US
Timezone	+00:00
Home URL	https://site.xyz
Site URL	https://site.xyz
Permalink structure	/%postname%/
Is this site using HTTPS?	Yes
Is this a multisite?	No
Can anyone register on this site?	No
Is this site discouraging search engines?	Yes
Default comment status	Open
Environment type	local
User count	2
Communication with WordPress.org	WordPress.org is reachable
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kirtangajjar** [comment] 2024-09-08 23:59
@vikrampm1 Although I didn't have access to shared hosting, but I tried to replicate the issue in my local with shown configuration and I wasn't able to reproduce it.

**Comment by vikrampm1** [comment] 2024-09-09 00:58
@ankitguptaindia @qasumitbagthariya can you double check to see if you are able to reproduce this issue? If not, then we can go ahead and close the issue.

**Closed as not planned** 2024-09-09 15:00 UTC
Labels: type:bug, help wanted

**Comment by qasumitbagthariya** [comment] 2024-09-09 17:08
@vikrampm1 

I tried to replicate the issue locally but was unable to reproduce it. I also cross-checked with WordPress versions 6.5.4 and 6.6.1.

WordPress 6.5.4

https://github.com/user-attachments/assets/4419d030-b799-4aa2-9d74-77f2cada994c

WordPress 6.6.1

https://github.com/user-attachments/assets/a853d1eb-1a6e-4228-9f01-08e9ed98d561
