### ISSUE TITLE
Push page build in divi builder but doesn't push images with it 

### ISSUE THREAD

**Issue by ccvision** [10up/distributor#812] opened 2021-10-21 09:24 UTC
I have build a page in divi builder but distributor doesn't push the images in my slider to the other pages.
Fix for this?

**Comment by jeffpaul** [comment] 2021-10-22 20:03
@ccvision this is a known issue with page builders, you can follow #348 to see when that gets resolved.  Closing this as a duplicate of 348.

**Closed as completed by jeffpaul** 2021-10-22 20:03 UTC
Labels: type:question
