### ISSUE TITLE
External connections do not distribute media

### ISSUE THREAD

**Issue by peterwilsoncc** [10up/distributor#975] opened 2022-11-22 03:15 UTC
### Describe the bug

When pushing or pulling content from an external connection, no media is distributed regardless of the settings in the admin.

This occurs regardless of whether the featured image is attached to the post or not.

Internal/network connections do distribute the featured images.

**Updates:**
* Please note that it seems to be more of an issue with in-content images and not featured images.
* See the test results in https://github.com/10up/distributor/issues/975#issuecomment-1382566549 and work on their fixes.

### Steps to Reproduce

1. Create two sites single sites running Distributor
2. Connect them bidirectionally (ie, so each site has the other as an external connection)
3. Create a post on one site
4. Add and in-content image(s)
5. publish the post
6. Either
   a. Push the post from the first sites screen
   b. Pull the post from the second sites admin
9. Open the pulled post in the editor, and observe there is no in-content image(s).

### Screenshots, screen recording, code snippet

**Source site**
![Screen Shot 2022-11-22 at 2 09 03 pm](https://user-images.githubusercontent.com/519727/203212356-24704be1-c967-4bc4-918c-2159d69f3b2a.png)

**Pulled content**
![Screen Shot 2022-11-22 at 2 10 15 pm](https://user-images.githubusercontent.com/519727/203212373-155c6160-f304-47d6-b07f-9bacbf0cf9ca.png)

**Pushed content**
![Screen Shot 2022-11-22 at 2 11 10 pm](https://user-images.githubusercontent.com/519727/203212383-b582e062-2190-4d94-8edf-013213d77a46.png)

### WordPress information

- Distributor Develop (at 3bb3e3f0f73573b6e7586478530b97568c4db430 )
- WordPress 6.1.1

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gleysen** [comment] 2023-01-11 16:08
Hope this gets fixed soon.. really need this as well...

**Comment by faisal-alvi** [comment] 2023-01-12 09:20
@peterwilsoncc I've performed the steps you suggested above, and I've seen that media is distributed between external connections without any problems (Tested on the "develop" branch). Please have a look at the video and let me know if there is anything I missed.

https://user-images.githubusercontent.com/25176325/212026447-bad4f4b7-30c7-4591-a2c9-d0df4f49a5b1.mp4

**Comment by gleysen** [comment] 2023-01-12 09:33
Hey Faisal,
Thank you for the response, I looked at the video, and this is also working for me.However, the problem I had is with images inside ACF fields. Most of my clients posts are extended with ACF fields to add photo's or have ACF wysiwyg fields to add content (with the possibility to add images in there)And those images don't get synced.

**Comment by gleysen** [comment] 2023-01-12 09:34
Hey Faisal,

Thank you for the response, I looked at the video, and this is also working
for me.
However, the problem I had is with images inside ACF fields. Most of my
clients posts are extended with ACF fields to add photo's or have ACF
wysiwyg fields to add content (with the possibility to add images in there)
And those images don't get synced.

G.





*Geert Leysen*Addict | Adventurer | Online Marketing Consultant
***@***.*** ***@***.***>*

**Comment by faisal-alvi** [comment] 2023-01-12 10:01
@gleysen thank you for the details. This seems to be a duplicate of #81. Closing this one, but if you have any further information that isn't included in #81, feel free to open it again.

**Comment by dkotter** [comment] 2023-01-13 22:59
So a few things here:

- The issue title here mentions how external connections aren't distributing media but the test steps only mention how featured images aren't working. From the tests @faisal-alvi has run, it seems like this (featured images) are working as expected now (can you verify this @peterwilsoncc?)
- We've had a few separate issues (most recently #993) that mention in-content images aren't getting transferred though the featured image is
- And the most recent follow up on this issue is around ACF, which is a known issue with Distributor right now (so something we want to eventually solve but not necessarily part of the investigation here)

I have run some tests myself with just in-content images and I've found some issues (see below). As such I'm reopening this issue. **Note** we may want to update the description of this issue to make it more clear that it seems to be more of an issue with in-content images and not featured images.

All tests were run with the setting `Process the featured image and any attached images` turned on for both sites as well as running Distributor v1.9.0

**Internal Connections**
- Push
   - Block editor
      - Image was added to the media library ✅ but the URL in the content still referenced the original site ❌ 
   - Classic editor
      - Image was added to the media library ✅ but the URL in the content still referenced the original site ❌
- Pull
   - Block editor
      - Image was added to the media library ✅ but the URL in the content still referenced the original site ❌ 
   - Classic editor
      - Image was added to the media library ✅ but the URL in the content still referenced the original site ❌ 

**External Connections**
- Push
   - Block editor
      - Image not pushed at all ❌ 
   - Classic editor
      - Image not pushed at all ❌
- Pull
   - Block editor
      - Image was added to the media library ✅ but the URL in the content still referenced the original site ❌ 
   - Classic editor
      - Image was added to the media library ✅ but the URL in the content still referenced the original site ❌ 

So from my testing, not a single scenario passed entirely. Most of them distributed the image as expected but just didn't update the URL in the content to reference the new site. But Pushing content to an external connection didn't do anything with media.

I still need to investigate why this is happening (unless someone else gets to this first) but definitely seems to be a problem. For reference, this setting was added in #184, so may be worth looking at that to get a sense of where to start.

**Comment by dkotter** [comment] 2023-01-25 19:19
Following up on the ^ above, I refreshed my memory even further on this and most of the above failures are expected (though would still be great to get fixed).

See #152 as well as this [comment](https://github.com/10up/distributor/issues/161#issuecomment-409949679) for more details but the current approach will send images over (if the setting is in place) but won't actually update the image URLs in the content (as there's more to still figure out there on how best to handle this).

So looks like the main failure here that isn't already known is Pushing to External Connections, as that doesn't seem to send images at all.

**Comment by kirtangajjar** [comment] 2023-03-12 18:18
@dkotter I had a look at it and I found that for pushing, the featured image does not appear while debugging locally, but it does appear if both sites are publically available. The root cause of the issue seemed to be the fact that the SSL certificates on localhost are self-signed (which does not get recognised by the PHP container). To test this issue, I have created two different WP instances on my server. 

The credentials are available [here](https://transfer.10up.com/ede190872204). (Both sites and the server is temporary so it's okay to expose them publically for time being).

**Comment by peterwilsoncc** [comment] 2023-07-06 05:29
@faisal-alvi @dkotter I came back to this while looking at another PR. 

The reason I was not seeing features images in an external pull request was because my local was set up to use content URLs with a relative scheme `//example.com/wp-content/upload/.../ben-platt.jpg` 

In WordPress this fails because WordPress isn't a browser so there is no scheme to be relative to ([code reference](https://github.com/wordPress/wordpress/blob/770f413fe7d0fcd87e0ab5afae32d1bc3a076f9e/wp-includes/class-wp-http.php#L275-L280)).

In this block of code, Distributor should check for relative URLs and add a scheme if there isn't one set

https://github.com/10up/distributor/blob/ba8834c2a1e47689763e877c442a57b579546159/includes/utils.php#L925-L935

Technically, there is no reason an `http` URL needs to produce the same result as its `https` counterpart. However, I think it is safe to assume that they will match for a typical WordPress site. 

I suggest we default to an `http` URL as `download_url` follows redirects and will download the final destination.

**Comment by faisal-alvi** [comment] 2023-08-08 11:39
@roshniahuja I see you self-assigned this ticket. Please note that I have updated the description to mention that the issue is with the in-content images and not featured images. Also, please see https://github.com/10up/distributor/issues/975#issuecomment-1382566549 for more details if you haven't already.

**Comment by roshniahuja** [comment] 2023-08-08 14:39
@faisal-alvi , I am not working on this task anymore so I removed my self from this task.

Thanks..!!

**Comment by jeffpaul** [comment] 2023-09-13 01:51
Closing via #1110

**Closed as completed by jeffpaul** 2023-09-13 01:51 UTC
Labels: type:bug, help wanted, needs:engineering, nice-to-have
