### ISSUE TITLE
Filter Connection By Category

### ISSUE THREAD

**Issue by cousett** [10up/distributor#1210] opened 2024-03-26 16:51 UTC
### Is your enhancement related to a problem? Please describe.

Not a problem just a new feature that would make life easier!

### Describe alternatives you've considered

My use case is to add niche content on certain sites. It would be so helpful if we could filter by a pulled category before it even displays a preview. My use case, I have 480 posts, only 68 are marked with the category I want. If I was able to filter I would have been able to pull just those 68 and not have to go thru pages of content to find the 68 posts. 
Thank you for this plugin!! It is 90% of what I need and I can work with it to do what I want!! 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jeffpaul** [comment] 2024-06-20 12:51
Closing as duplicate of #428.

**Closed as not planned by jeffpaul** 2024-06-20 12:51 UTC
Labels: type:enhancement
